export const CATEGORIES: Record<number, 
string> = {
    0: "Utilities", 
    1: "Health", 
    2: "Dining", 
    3: "Travel", 
    4: "Education", 
    5: "Subscription", 
    6: "Family", 
    7: "Food", 
    8: "Festivals", 
    9: "Culture", 
    10: "Apparel", 
    11: "Transportation", 
    12: "Investment", 
    13: "Shopping", 
    14: "Groceries", 
    15: "Documents", 
    16: "Grooming", 
    17: "Entertainment", 
    18: "Social life", 
    19: "Beauty", 
    20: "Rent", 
    21: "Money transfer", 
    22: "Salary", 
    23: "Tourism", 
    24: "Household",
    25: "Other"
};

export const CATEGORY_VALUES = Object.values(CATEGORIES);
