from typing import Dict


KNOWN_MERCHANT_CATEGORIES:Dict[str, str] = {
    "sklavenitis": "Groceries",
    "ab shop  go": "Groceries",
    "abshopngo": "Groceries",
    "acs": "Shopping",
    "aegean": "Transportation",
    "admiral": "Apparel",
    "airbnb": "Tourism",
    "aliexpress": "Shopping",
    "amazon": "Shopping",
    "apollonion": "Food",
    "attiki odos": "Transportation",
    "bazaar": "Groceries",
    "benetis": "Food",
    "bershka": "Apparel",
    "blue star": "Transportation",
    "bookingcom": "Tourism",
    "cine": "Entertainment",
    "coffee island": "Food",
    "cosmote": "Utilities",
    "ebay": "Shopping",
    "economy markets": "Groceries",
    "skroutz": "Shopping",
    "everest": "Food",
    "farmakeio": "Health",
    "galaxias": "Groceries",
    "germanos": "Utilities",
    "goodys": "Dining",
    "hm": "Apparel",
    "hondos center": "Shopping",
    "iatro": "Health",
    "il toto": "Food",
    "jumbo": "Shopping",
    "jysk": "Household",
    "kfc": "Food",
    "kosmodata": "Utilities",
    "ktel": "Transportation",
    "mark aalen": "Health",
    "market in": "Groceries",
    "marks  spencer": "Shopping",
    "masoutis": "Groceries",
    "massimo dutti": "Apparel",
    "mcdonald": "Food",
    "megafit": "Subscription",
    "mk kiosk": "Shopping",
    "my market": "Groceries",
    "nea odos a e": "Transportation",
    "nike": "Apparel",
    "oasa eticket pos": "Transportation",
    "odos kentrikis ellad": "Transportation",
    "ok anytime": "Transportation",
    "ottika": "Health",
    "souvlaki": "Food",
    "periptero": "Food",
    "plaisio": "Shopping",
    "pliromi asfalistron": "Transportation",
    "plus market": "Groceries",
    "polimarket": "Groceries",
    "public": "Shopping",
    "pull  bear": "Apparel",
    "pullandbear": "Apparel",
    "pullbear": "Apparel",
    "revolut": "Money transfer",
    "shell": "Transportation",
    "sm krhtikos": "Groceries",
    "sneaker10": "Apparel",
    "starbucks": "Dining",
    "telis kikeris": "Grooming",
    "the magic box": "Groceries",
    "vero foumo": "Social life",
    "wolt": "Food",
    "zakcret": "Apparel",
    "zara": "Apparel",
    "εμb ": "Money transfer",
    "εντολη/εμβασμα σε αλλη τραπεζα": "Money transfer",
    "εξοδα τρ πληρωμης": "Utilities",
    "μεταφορα σε λογαριασμο ete": "Money transfer",
    "e παραβολο": "Documents",
    "interamerican": "Transportation",
    "δ.ε.η.": "Utilities",
    "ikea": "Household",
    "vinted": "Shopping",
    "village": "Entertainment",
}

CATEGORIES:Dict[int, str] = {
    0: "Utilities",
    1: "Health",
    2: "Dining",
    3: "Travel",
    4: "Education",
    5: "Subscription",
    6: "Family",
    7: "Food",
    8: "Festivals",
    9: "Culture",
    10: "Apparel",
    11: "Transportation",
    12: "Investment",
    13: "Shopping",
    14: "Groceries",
    15: "Documents",
    16: "Grooming",
    17: "Entertainment",
    18: "Social life",
    19: "Beauty",
    20: "Rent",
    21: "Money transfer",
    22: "Salary",
    23: "Tourism",
    24: "Household",
}

label2id = {v: k for k, v in CATEGORIES.items()}
id2label = {k: v for k, v in CATEGORIES.items()}
